server:
  port: 8081

security:
  oauth2:
    client:
      client-id: my_app
      client-secret: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application :
    name: MANAGEMENT-SERVICE
  jpa:
    hibernate:
      ddl-auto: validate #  is important. It tries to validate the database schema according to the entities that ->
      #you have created in the application and throws an error if the schema doesn’t match the entity specifications.
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect #to provide the configuration of SQL MyISAM and InnoDB.
    show-sql: true
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/flyway?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345
  kafka:
    producer:
      bootstarp-servers: locahost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
